/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conf.Conexao;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author marcos
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    public Conexao conexao;    
    public static Statement stmt;

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() throws SQLException {
        
        conexao = new Conexao();        
        stmt = conexao.getConexao().createStatement();
        
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonCadastroContatos = new javax.swing.JButton();
        jButtonControleUsuarios = new javax.swing.JButton();
        jButtonListagemContatos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroContatos = new javax.swing.JMenuItem();
        jMenuSeguranca = new javax.swing.JMenu();
        jMenuItemCadastroUsuarios = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemListagemContatos = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Clientes - Horizontis");

        jToolBar1.setRollover(true);

        jButtonCadastroContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Clientes.gif"))); // NOI18N
        jButtonCadastroContatos.setText("Contatos");
        jButtonCadastroContatos.setFocusable(false);
        jButtonCadastroContatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastroContatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadastroContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroContatosActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonCadastroContatos);

        jButtonControleUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Fornecedores.gif"))); // NOI18N
        jButtonControleUsuarios.setText("Usuários");
        jButtonControleUsuarios.setFocusable(false);
        jButtonControleUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonControleUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonControleUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonControleUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonControleUsuarios);

        jButtonListagemContatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Relatórios.png"))); // NOI18N
        jButtonListagemContatos.setText("Listagem de Contatos");
        jButtonListagemContatos.setFocusable(false);
        jButtonListagemContatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonListagemContatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonListagemContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListagemContatosActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonListagemContatos);
        jToolBar1.add(jSeparator1);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair01.gif"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setFocusable(false);
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSair);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroContatos.setText("Contatos");
        jMenuItemCadastroContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroContatosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroContatos);

        jMenuBar1.add(jMenuCadastro);

        jMenuSeguranca.setText("Segurança");

        jMenuItemCadastroUsuarios.setText("Controle de Usuários");
        jMenuItemCadastroUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuariosActionPerformed(evt);
            }
        });
        jMenuSeguranca.add(jMenuItemCadastroUsuarios);

        jMenuBar1.add(jMenuSeguranca);

        jMenuRelatorios.setText("Relatórios");

        jMenuItemListagemContatos.setText("Listagem de Contatos");
        jMenuItemListagemContatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListagemContatosActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemListagemContatos);

        jMenuBar1.add(jMenuRelatorios);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuSairMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroContatosActionPerformed
        // TODO add your handling code here:
        FormCadastroContatos formCadContatos = null;
        try {
            formCadContatos = new FormCadastroContatos();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        java.awt.Dimension tamanhoTela =
                formCadContatos.getPreferredSize();
        java.awt.Dimension tamanhoFrame = getSize();

        java.awt.Point loc = getLocation();
        formCadContatos.setLocation(
                (tamanhoFrame.width - tamanhoTela.width) / 2 + loc.x,
                (tamanhoFrame.height - tamanhoTela.height) / 2 + loc.y);
        formCadContatos.pack();
        formCadContatos.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroContatosActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        encerrarSistema();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jMenuSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMousePressed
        // TODO add your handling code here:
        encerrarSistema();
    }//GEN-LAST:event_jMenuSairMousePressed

    private void jMenuItemCadastroUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuariosActionPerformed
        // TODO add your handling code here:
        FormCadastroUsuarios formCadUsuarios = null;
        try {
            formCadUsuarios = new FormCadastroUsuarios();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        java.awt.Dimension tamanhoTela =
                formCadUsuarios.getPreferredSize();
        java.awt.Dimension tamanhoFrame = getSize();

        java.awt.Point loc = getLocation();
        formCadUsuarios.setLocation(
                (tamanhoFrame.width - tamanhoTela.width) / 2 + loc.x,
                (tamanhoFrame.height - tamanhoTela.height) / 2 + loc.y);
        formCadUsuarios.pack();
        formCadUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroUsuariosActionPerformed

    private void jButtonCadastroContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroContatosActionPerformed
        // TODO add your handling code here:
        jMenuItemCadastroContatosActionPerformed(evt);
    }//GEN-LAST:event_jButtonCadastroContatosActionPerformed

    private void jButtonControleUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonControleUsuariosActionPerformed
        // TODO add your handling code here:
        jMenuItemCadastroUsuariosActionPerformed(evt);
    }//GEN-LAST:event_jButtonControleUsuariosActionPerformed

    private void jMenuItemListagemContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListagemContatosActionPerformed
        // TODO add your handling code here:
        imprimir("ListagemContatos.jasper");
    }//GEN-LAST:event_jMenuItemListagemContatosActionPerformed

    private void jButtonListagemContatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListagemContatosActionPerformed
        // TODO add your handling code here:
        imprimir("ListagemContatos.jasper");
    }//GEN-LAST:event_jButtonListagemContatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormPrincipal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void encerrarSistema() {
        int opcao = JOptionPane.showConfirmDialog(this,
                "Deseja realmente sair do sistema?",
                "Encerrar Aplicação",
                JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    
    public void imprimir(String relatorio) {
        JasperPrint relat;
        try {
            JDialog viewer = new 
                    JDialog(new javax.swing.JFrame(), 
                    "Curso da Horizontis - Visualização do Relatório", true);
            viewer.setSize(900, 600);
            viewer.setLocationRelativeTo(null);

            relat = gerar(relatorio);
            JasperViewer jrViewer = new JasperViewer(relat, true);
            viewer.getContentPane().add(jrViewer.getContentPane());
            viewer.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public JasperPrint gerar(String arquivoJasper) {
        JasperPrint rel = null;
        try {
            HashMap map = new HashMap();
            
            rel = JasperFillManager.fillReport(arquivoJasper, map, conexao.getConexao());
        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return rel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroContatos;
    private javax.swing.JButton jButtonControleUsuarios;
    private javax.swing.JButton jButtonListagemContatos;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemCadastroContatos;
    private javax.swing.JMenuItem jMenuItemCadastroUsuarios;
    private javax.swing.JMenuItem jMenuItemListagemContatos;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSeguranca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
